language: php
php:
  - 5.6
  - hhvm
  - nightly
  - 7

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: nightly
    - php: 7
  fast_finish: true

script: phpunit --bootstrap tests/bootstrap.php tests

notifications:
    on_success: never
    on_failure: always
